### ISSUE TITLE
shp2ceterline issue

### ISSUE THREAD

**Issue by vufalo1995** [fitodic/centerline#10]
Hi folks,
I've already set up all the requirements and follow the instructions in order to run the code but:
My system (windows32) is not able to find shp2centerline script. Do I need to change the extension of that file? Maybe should I try to run it as *.py?

**Comment by fitodic** [comment]
@vufalo1995 First of all, sorry for the delay.

I haven't used Windows for quite some time, but I do seem to recall that after installing Python, [the path to its executable should be added to the Windows' PATH environment variable](
https://docs.python.org/2/faq/windows.html#how-do-i-make-python-scripts-executable) in order to run scripts without the `py` extension. Have you tried that?
