### ISSUE TITLE
Problems to create centerline when I have used Multipolygon

### ISSUE THREAD

**Issue by cesar3158** [fitodic/centerline#28]
Hi....

I have read on centerline documentation and is possible to use Multipolygon to calculate the centerline, rigth?
I have a shapefile containing 1328 polygons on the file and the type of this, acoording python is "**print(type(Multi)) <class 'shapely.geometry.multipolygon.MultiPolygon'>**"
When I have tried execute the comandline the Python returns an error that is showing below:

> Multi = MultiPolygon([shape(pol['geometry']) for pol in fiona.open('Plantio_Cana_NDVI_Preparado_Final.shp')])
centerln = centerline.geometry.Centerline(Multi,interpolation_distance=0.5)

> 

Error on python:

    **centerln = centerline.geometry.Centerline(Multi,interpolation_distance=0.5)

AttributeError: module 'centerline' has no attribute 'geometry'**

Could you help me to understand this issue?

**Comment by fitodic** [comment]
Hi @cesar3158,

`AttributeError: module 'centerline' has no attribute 'geometry'**` is raised when the package is imported. Unfortunately, this [doesn't implicitly import all of its modules](https://docs.python.org/3/tutorial/modules.html?#importing-from-a-package). To achieve that, the `centerline/__init__.py` module would have to contain the following:

```python
from . import converters, exceptions, geometry
# ...
__all__ = ["converters", "exceptions", "geometry"]
```

The reason this isn't defined is because it prevents the package build due to third-party libraries that are imported in these modules, but otherwise not necessary for the build. It's one of the downsides of Python's `import` system and `setuptools` that concerns the build process.

To avoid this, I suggest you use `from centerline.geometry import Centerline`.

**Comment by cesar3158** [comment]
Hi @fitodic, thank you for help me!!! I just arrived at the company and I did the modification on importation the certerline function and the error doen't occur more.
How I'm running the centerline to about 1500 polygons, I don't have the centerlines created but when I have conclude here I will tell you.

Thank you a lot again.

César de Paula

**Comment by fitodic** [comment]
You're welcome :slightly_smiling_face:
